manifest:
  defaults:
    remote: github
    revision: master

  remotes:
    - name: github
      url-base: ssh://git@github.com

    - name: openembedded
      url-base: git://git.openembedded.org

    - name: yoctoproject
      url-base: git://git.yoctoproject.org

  projects:
    - name: linux-sunxi/meta-sunxi
      path: meta-sunxi

    - name: meta-openembedded
      path: meta-openembedded
      remote: openembedded
      revision: thud

    - name: poky
      path: poky
      remote: yoctoproject
      revision: refs/tags/yocto-3.0.2

  self:
    path: meta-m1cha
    west-commands: scripts/west-commands.yml

  configs:
    zephyr:
      disabled: true